<?php
namespace app\controllers\api;


use app\components\base\Entity;
use app\models\register\Parsing;
use yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class ImportController extends Controller
{

    /**
     * @inheritdoc
     */
    public function actions()
    {

        $this->enableCsrfValidation = false;
        $entities = Entity::getEnumArray();
        
        $actions = [];

        foreach ($entities as $entity) {
            $actions[$entity['action']] = [
                'class'         => 'app\components\api\actions\ImportAction',
                'modelClass'    => $entity['class_name'],
            ];
        }
        
        return $actions;
    }
    

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {

        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow'     => true,
                    ],
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'import' => ['get','post'],
                    'parsed' => ['get','post'],
                    'parsing-done' => ['get','post'],
                ],
            ],
        ];
    }

    /**
     * Обратная совместимость
     * @deprecated
     */
    public function actionParsed()
    {
        return Yii::$app->runAction('api/cd/parsed');
    }
    
    /**
     * Обратная совместимость
     * @deprecated
     */
    public function actionParsingDone($parsing_id)
    {
        Parsing::parsingFinished($parsing_id);
        return "ok";
    }
}