<?php

use App\EmployeesPosition;
use Illuminate\Database\Seeder;

class EmployeesPositionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $positions = [
        	['id' => 1,   'name' => 'Системный аналитик',										'department_id' => 3],
        	['id' => 2,   'name' => 'Программист',												'department_id' => 3],
        	['id' => 6,   'name' => 'Вице-президент по оперативному управлению',				'department_id' => 34],
        	['id' => 7,   'name' => 'Председатель комитета по делам молодежи',					'department_id' => 7],
        	['id' => 8,   'name' => 'Вице-президент по развитию',								'department_id' => 34],
        	['id' => 10,  'name' => 'Диспетчер',												'department_id' => 8],
        	['id' => 11,  'name' => 'Начальник УМУ',											'department_id' => 8],
        	['id' => 12,  'name' => 'Советник президента по УМР',								'department_id' => 8],
        	['id' => 13,  'name' => 'Старший методист УМУ',										'department_id' => 8],
        	['id' => 14,  'name' => 'Методист УМУ',												'department_id' => 8],
        	['id' => 15,  'name' => 'Специалист по мониторингу и оценке языкового образования', 'department_id' => 8],
        	['id' => 16,  'name' => 'Старший диспетчер',										'department_id' => 8],
        	['id' => 17,  'name' => 'Технический секретарь УМУ',								'department_id' => 8],
        	['id' => 18,  'name' => 'Директор ОИЦ',												'department_id' => 8],
        	['id' => 19,  'name' => 'Директор ОР',												'department_id' => 9],
        	['id' => 20,  'name' => 'Старший ОР',												'department_id' => 9],
        	['id' => 21,  'name' => 'ОР',														'department_id' => 9],
        	['id' => 22,  'name' => 'Ассистент отдела ОР',										'department_id' => 9],
        	['id' => 36,  'name' => 'Главный бухгалтер',										'department_id' => 11],
        	['id' => 37,  'name' => 'Бухгалтер по контингенту',									'department_id' => 11],
        	['id' => 38,  'name' => 'Материальный бухгалтер',									'department_id' => 11],
        	['id' => 39,  'name' => 'Расчетный бухгалтер',										'department_id' => 11],
        	['id' => 40,  'name' => 'Бухгалтер-кассир',											'department_id' => 11],
        	['id' => 41,  'name' => 'Специалист отдела маркетинга',								'department_id' => 12],
        	['id' => 43,  'name' => 'И.о.заведующей отделом магистратуры',						'department_id' => 14],
        	['id' => 44,  'name' => 'Специалист отдела магистратуры',							'department_id' => 14],
        	['id' => 45,  'name' => 'Начальник административно-хозяйственной части',			'department_id' => 15],
        	['id' => 46,  'name' => 'Сотрудник административно-хозяйственной части',			'department_id' => 15],
        	['id' => 47,  'name' => 'Водитель',													'department_id' => 15],
        	['id' => 48,  'name' => 'Заведующий здравпунктом',									'department_id' => 16],
        	['id' => 49,  'name' => 'Заведующая студенческой канцелярией',						'department_id' => 17],
        	['id' => 50,  'name' => 'Специалист студенческой канцелярии',						'department_id' => 17],
        	['id' => 51,  'name' => 'Директор НИЦ',												'department_id' => 18],
        	['id' => 52,  'name' => 'Заместитель директора НИЦ',								'department_id' => 18],
        	['id' => 53,  'name' => 'Архивариус',												'department_id' => 19],
        	['id' => 54,  'name' => 'Старший специалист центра обслуживания студентов',			'department_id' => 20],
        	['id' => 55,  'name' => 'Специалист центра обслуживания студентов',					'department_id' => 20],
        	['id' => 56,  'name' => 'Директор центра тестирования',								'department_id' => 21],
        	['id' => 58,  'name' => 'Секретарь-референт',										'department_id' => 6],
        	['id' => 59,  'name' => 'Технический секретарь приемной комиссии',					'department_id' => 22],
        	['id' => 60,  'name' => 'Заведующий лабораторией',									'department_id' => 37],
        	['id' => 61,  'name' => 'Ассистент кафедры',										'department_id' => 36],
        	['id' => 70,  'name' => 'Лаборант кафедры',											'department_id' => 41],
        	['id' => 71,  'name' => 'Старший вахтер',											'department_id' => 15],
        	['id' => 72,  'name' => 'Системный администратор',									'department_id' => 47],
        	['id' => 117, 'name' => 'Лаборант компьютерного зала',								'department_id' => 3],
        	['id' => 118, 'name' => 'Оператор центра тестирования',								'department_id' => 21],
        	['id' => 130, 'name' => 'Профессор',												'department_id' => 40],
        	['id' => 131, 'name' => 'Ассоцированный профессор',									'department_id' => 40],
        	['id' => 132, 'name' => 'Доцент',													'department_id' => 30],
        	['id' => 133, 'name' => 'Преподаватель',											'department_id' => 38],
        	['id' => 134, 'name' => 'Старший преподаватель',									'department_id' => 38],
        	['id' => 136, 'name' => 'Администратор',											'department_id' => 15],
        	['id' => 137, 'name' => 'Дворник',													'department_id' => 15],
        	['id' => 138, 'name' => 'Техничка',													'department_id' => 15],
        	['id' => 139, 'name' => 'Подсобный рабочий',										'department_id' => 15],
        	['id' => 140, 'name' => 'Вахтер',													'department_id' => 15],
        	['id' => 142, 'name' => 'Оператор',													'department_id' => 21],
        	['id' => 144, 'name' => 'Инженер',													'department_id' => 41],
        	['id' => 145, 'name' => 'Арт-директор',												'department_id' => 12],
        	['id' => 146, 'name' => 'Дизайнер',													'department_id' => 12],
        	['id' => 147, 'name' => 'Помощник маркетолога',										'department_id' => 12],
        	['id' => 148, 'name' => 'Специалист по языкам',										'department_id' => 8],
        	['id' => 149, 'name' => 'Советник по юридическим вопросам',							'department_id' => 34],
        	['id' => 153, 'name' => 'Проректор по социальной работе и международным связям',	'department_id' => 58],
        	['id' => 154, 'name' => 'Проректор по НИР и инновациям',							'department_id' => 58],
        	['id' => 155, 'name' => 'Проректор по МС',											'department_id' => 6],
        	['id' => 156, 'name' => 'Секретарь Ученого Совета',									'department_id' => 6],
        	['id' => 157, 'name' => 'Финансовый директор',										'department_id' => 34],
        	['id' => 158, 'name' => 'Заведующий кафедрой',										'department_id' => 40],
        	['id' => 164, 'name' => 'Декан',													'department_id' => 46],
        	['id' => 166, 'name' => 'Внутренний аудитор',										'department_id' => 1],
        	['id' => 169, 'name' => 'Президент',												'department_id' => 34],
        	['id' => 170, 'name' => 'Проректор по учебной и учебно-методической работе',		'department_id' => 8],
        	['id' => 171, 'name' => 'Ректор',													'department_id' => 58],
        	['id' => 172, 'name' => 'Старший секретарь-референт',								'department_id' => 58],
        	['id' => 173, 'name' => 'Старший специалист студенческой канцелярией',				'department_id' => 17],
        	['id' => 175, 'name' => 'И.о.декана',												'department_id' => 46],
        	['id' => 176, 'name' => 'Техник',													'department_id' => 41],
        	['id' => 177, 'name' => 'Инженер ТБ',												'department_id' => 15],
        	['id' => 178, 'name' => 'Методист ОМ',												'department_id' => 14],
        	['id' => 179, 'name' => 'Консультант международного класса',						'department_id' => 34],
        	['id' => 181, 'name' => 'Финансовый аналитик',										'department_id' => 34],
        	['id' => 182, 'name' => 'Методист',													'department_id' => 48],
        	['id' => 183, 'name' => 'Координатор по работе со студентами',						'department_id' => 6],
        	['id' => 184, 'name' => 'Первый проректор',											'department_id' => 34],
        	['id' => 185, 'name' => 'И.о.заведующего кафедрой',									'department_id' => 50],
        	['id' => 186, 'name' => 'Специалист приемной комиссии',								'department_id' => 57],
        	['id' => 187, 'name' => 'Специалист отдела IT',										'department_id' => 3],
        	['id' => 188, 'name' => 'Старший методист УМУ',										'department_id' => 8],
        	['id' => 189, 'name' => 'Начальник штаба ГО',										'department_id' => 15],
        	['id' => 190, 'name' => 'Библиотекарь',												'department_id' => 8],
        	['id' => 191, 'name' => 'И.о.директора ОИЦ',										'department_id' => 8],
        	['id' => 192, 'name' => 'Старший Преподаватель',									'department_id' => 44],
        	['id' => 193, 'name' => 'Сварщик',													'department_id' => 15],
        	['id' => 195, 'name' => 'Проректор по хозяйственной деятельности и общим вопросам', 'department_id' => 58],
        	['id' => 196, 'name' => 'Помощник председателя КДМ',								'department_id' => 7],
        	['id' => 197, 'name' => 'Сотрудник АНК',											'department_id' => 6],
        	['id' => 198, 'name' => 'Помощник проректора по НИР',								'department_id' => 18],
        	['id' => 199, 'name' => 'Начальник ОАУК', 											'department_id' => 4]
        ];

        foreach ($positions as $value) {
        	EmployeesPosition::updateOrCreate($value);
        }
    }
}
