<?php


namespace app\components;


use kartik\base\BootstrapTrait;
use Yii;
use yii\bootstrap\ActiveForm;

class StubForm extends \kartik\form\ActiveForm
{
    public function isBs4() {
        return false;
    }

    public $layout = 'default';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}