<?php

use app\components\Schema;
use app\components\Migration;
use app\components\base\Entity;

class m190729_091644_080_enums extends Migration
{
    public function up()
    {
        $inserts = explode(";\n", $this->inserts);

        foreach ($inserts as $insert) {
            if (trim($insert)) {
                $this->db->createCommand($insert)->execute();
            }
        }
    }

    public function down()
    {
        $this->truncateTable('{{%entity}}');
        $this->truncateTable('{{%competition_mode}}');
        $this->truncateTable('{{%error_type}}');
        $this->truncateTable('{{%file_format}}');
        $this->truncateTable('{{%horadric_cube_status}}');
        $this->truncateTable('{{%parsing_status}}');
        $this->truncateTable('{{%price_former_type}}');
        $this->truncateTable('{{%price_export_mode}}');
        $this->truncateTable('{{%price_parsed_status}}');
        $this->truncateTable('{{%project_execution_status}}');
        $this->truncateTable('{{%select_price_logic}}');
        $this->truncateTable('{{%source}}');
        $this->truncateTable('{{%status}}');
        $this->truncateTable('{{%task_status}}');
        $this->truncateTable('{{%task_type}}');
        $this->truncateTable('{{%region}}');
    }

    public $inserts = <<<SQL
INSERT INTO {{%competition_mode}} (id, name, status_id) VALUES (1, 'Только выбранные конкуренты', 0);
INSERT INTO {{%competition_mode}} (id, name, status_id) VALUES (2, 'Только известные магазины', 0);
INSERT INTO {{%competition_mode}} (id, name, status_id) VALUES (3, 'Все магазины', 0);
INSERT INTO {{%competition_mode}} (id, name, status_id) VALUES (4, 'Первая цена по всем конкурентам региона', 0);

INSERT INTO {{%error_type}} (id, name, status_id) VALUES (0, 'Общая', 0);
INSERT INTO {{%error_type}} (id, name, status_id) VALUES (1, 'Импорт', 0);
INSERT INTO {{%error_type}} (id, name, status_id) VALUES (2, 'Экспорт', 0);
INSERT INTO {{%error_type}} (id, name, status_id) VALUES (3, 'Импорт из файла', 0);
INSERT INTO {{%error_type}} (id, name, status_id) VALUES (4, 'Экспорт в файл', 0);
INSERT INTO {{%error_type}} (id, name, status_id) VALUES (5, 'Процесс', 0);
INSERT INTO {{%error_type}} (id, name, status_id) VALUES (6, 'Парсинг', 0);
INSERT INTO {{%error_type}} (id, name, status_id) VALUES (7, 'Приём спарсенных цен', 0);
INSERT INTO {{%error_type}} (id, name, status_id) VALUES (8, 'Обработка спарсенных цен', 0);
INSERT INTO {{%error_type}} (id, name, status_id) VALUES (9, 'Ошибка стороннего API', 0);

INSERT INTO {{%file_format}} (id, name, mime_types, extensions, status_id) VALUES (1, 'CSV', 'text/csv', 'csv', 0);
INSERT INTO {{%file_format}} (id, name, mime_types, extensions, status_id) VALUES (2, 'XLS', 'application/x-xls,application/xls,application/vnd.ms-excel,application/msexcel,application/x-msexcel,application/x-ms-excel,application/x-excel,application/x-dos_ms_excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.google-apps.spreadsheet', 'xls,xlsx', 0);
INSERT INTO {{%file_format}} (id, name, mime_types, extensions, status_id) VALUES (3, 'JSON', 'application/json,application/javascript,application/x-javascript,text/javascript,text/x-javascript,text/x-json', 'json', 0);

INSERT INTO {{%horadric_cube_status}} (id, name, status_id) VALUES (1, 'Новый', 0);
INSERT INTO {{%horadric_cube_status}} (id, name, status_id) VALUES (2, 'Сопоставлен', 0);
INSERT INTO {{%horadric_cube_status}} (id, name, status_id) VALUES (3, 'Отфильтрован', 0);
INSERT INTO {{%horadric_cube_status}} (id, name, status_id) VALUES (4, 'Не соответствует', 0);

INSERT INTO {{%parsing_status}} (id, name, status_id) VALUES (1, 'Новый', 0);
INSERT INTO {{%parsing_status}} (id, name, status_id) VALUES (2, 'Файл создан', 0);
INSERT INTO {{%parsing_status}} (id, name, status_id) VALUES (3, 'В очереди', 0);
INSERT INTO {{%parsing_status}} (id, name, status_id) VALUES (4, 'В процессе', 0);
INSERT INTO {{%parsing_status}} (id, name, status_id) VALUES (5, 'Пауза', 0);
INSERT INTO {{%parsing_status}} (id, name, status_id) VALUES (6, 'Готово', 0);
INSERT INTO {{%parsing_status}} (id, name, status_id) VALUES (7, 'Отменён', 0);
INSERT INTO {{%parsing_status}} (id, name, status_id) VALUES (8, 'Не было проксей', 0);

INSERT INTO {{%price_export_mode}} (id, name, status_id) VALUES (1, 'Выгружать всю номенклатуру', 0);
INSERT INTO {{%price_export_mode}} (id, name, status_id) VALUES (3, 'РРЦ = 0 ИЛИ Рег.РРЦ', 0);
INSERT INTO {{%price_export_mode}} (id, name, status_id) VALUES (2, 'Только без РРЦ', 2);

INSERT INTO {{%price_parsed_status}} (id, name) VALUES (0, 'Новая');
INSERT INTO {{%price_parsed_status}} (id, name) VALUES (1, 'Обработана');
INSERT INTO {{%price_parsed_status}} (id, name) VALUES (2, 'Ошибка обработки');
INSERT INTO {{%price_parsed_status}} (id, name) VALUES (3, 'Отфильтрована');
INSERT INTO {{%price_parsed_status}} (id, name) VALUES (4, 'Сбор номенклатуры: Новое');
INSERT INTO {{%price_parsed_status}} (id, name) VALUES (5, 'Сбор номенклатуры: Отфильтрован');
INSERT INTO {{%price_parsed_status}} (id, name) VALUES (6, 'Сбор номенклатуры: На идентификацию ');
INSERT INTO {{%price_parsed_status}} (id, name) VALUES (7, 'Идентификация: Новая');
INSERT INTO {{%price_parsed_status}} (id, name) VALUES (8, 'Идентификация: Отфильтрована');
INSERT INTO {{%price_parsed_status}} (id, name) VALUES (9, 'Идентификация: На ручной разбор');
INSERT INTO {{%price_parsed_status}} (id, name) VALUES (10, 'Не сопоставлен с товаром ВИ');
INSERT INTO {{%price_parsed_status}} (id, name) VALUES (11, 'Идентификация: Сопоставлен автоматически');

INSERT INTO {{%project_execution_status}} (id, name, status_id) VALUES (3, 'В очереди', 0);
INSERT INTO {{%project_execution_status}} (id, name, status_id) VALUES (4, 'Расчитывается', 0);
INSERT INTO {{%project_execution_status}} (id, name, status_id) VALUES (5, 'Расчет на паузе', 0);
INSERT INTO {{%project_execution_status}} (id, name, status_id) VALUES (6, 'Цены расчитаны', 0);
INSERT INTO {{%project_execution_status}} (id, name, status_id) VALUES (7, 'Экспотируется', 0);
INSERT INTO {{%project_execution_status}} (id, name, status_id) VALUES (8, 'Экспорт на паузе', 0);
INSERT INTO {{%project_execution_status}} (id, name, status_id) VALUES (9, 'Цены экспортированы', 0);
INSERT INTO {{%project_execution_status}} (id, name, status_id) VALUES (10, 'Закрыт', 0);
INSERT INTO {{%project_execution_status}} (id, name, status_id) VALUES (11, 'Подготовка к расчету', 0);
INSERT INTO {{%project_execution_status}} (id, name, status_id) VALUES (12, 'Цены актуализированы', 0);
INSERT INTO {{%project_execution_status}} (id, name, status_id) VALUES (1, 'Новый', 0);
INSERT INTO {{%project_execution_status}} (id, name, status_id) VALUES (2, 'Готов', 0);
INSERT INTO {{%project_execution_status}} (id, name, status_id) VALUES (13, 'Подготовка приостановлена', 0);

INSERT INTO {{%select_price_logic}} (id, name, alias, status_id) VALUES (101, 'A', 'A', 0);
INSERT INTO {{%select_price_logic}} (id, name, alias, status_id) VALUES (102, 'B', 'B', 0);
INSERT INTO {{%select_price_logic}} (id, name, alias, status_id) VALUES (103, 'C', 'C', 0);
INSERT INTO {{%select_price_logic}} (id, name, alias, status_id) VALUES (1, '1', '1', 0);
INSERT INTO {{%select_price_logic}} (id, name, alias, status_id) VALUES (2, '2', '2', 0);
INSERT INTO {{%select_price_logic}} (id, name, alias, status_id) VALUES (3, '3', '3', 0);
INSERT INTO {{%select_price_logic}} (id, name, alias, status_id) VALUES (4, '4', '4', 0);
INSERT INTO {{%select_price_logic}} (id, name, alias, status_id) VALUES (5, '5', '5', 0);
INSERT INTO {{%select_price_logic}} (id, name, alias, status_id) VALUES (7, '7', '7', 0);
INSERT INTO {{%select_price_logic}} (id, name, alias, status_id) VALUES (8, '8', '8', 0);
INSERT INTO {{%select_price_logic}} (id, name, alias, status_id) VALUES (9, '9', '9', 0);
INSERT INTO {{%select_price_logic}} (id, name, alias, status_id) VALUES (10, '10', '10', 0);

INSERT INTO {{%source}} (id, name, status_id) VALUES (1, 'Яндекс.Маркет', 0);
INSERT INTO {{%source}} (id, name, status_id) VALUES (2, 'Сайты', 0);

INSERT INTO {{%status}} (id, name) VALUES (0, 'Активен');
INSERT INTO {{%status}} (id, name) VALUES (1, 'Удалён');
INSERT INTO {{%status}} (id, name) VALUES (2, 'Отключён');

INSERT INTO {{%task_status}} (id, name, icon, status_id) VALUES (1, 'Новый', 'fa fa-asterisk', 0);
INSERT INTO {{%task_status}} (id, name, icon, status_id) VALUES (2, 'В очереди', 'fa fa-clock-o', 0);
INSERT INTO {{%task_status}} (id, name, icon, status_id) VALUES (3, 'Выполняется', 'fa fa-spin fa-spinner', 0);
INSERT INTO {{%task_status}} (id, name, icon, status_id) VALUES (4, 'Пауза', 'fa fa-pause', 0);
INSERT INTO {{%task_status}} (id, name, icon, status_id) VALUES (5, 'Ожидает', 'fa fa-hourglass-half', 0);
INSERT INTO {{%task_status}} (id, name, icon, status_id) VALUES (6, 'Выполнен', 'fa fa-check-square-o', 0);
INSERT INTO {{%task_status}} (id, name, icon, status_id) VALUES (7, 'Отменён', 'fa fa-trash-o', 0);
INSERT INTO {{%task_status}} (id, name, icon, status_id) VALUES (8, 'Не удалось выполнить', 'fa-exclamation-triangle', 0);

INSERT INTO {{%task_type}} (id, name, icon, status_id) VALUES (1, 'Общий', 'fa fa-tasks', 0);
INSERT INTO {{%task_type}} (id, name, icon, status_id) VALUES (2, 'Синхронизация', 'fa fa-cloud', 0);
INSERT INTO {{%task_type}} (id, name, icon, status_id) VALUES (3, 'Импорт', 'fa fa-download', 0);
INSERT INTO {{%task_type}} (id, name, icon, status_id) VALUES (4, 'Обработка парсинга', 'fa fa-rub', 0);
INSERT INTO {{%task_type}} (id, name, icon, status_id) VALUES (5, 'Автозаполнение проекта', 'fa fa-cloud', 0);
INSERT INTO {{%task_type}} (id, name, icon, status_id) VALUES (6, 'Обновление цен', 'fa fa-refresh', 0);
INSERT INTO {{%task_type}} (id, name, icon, status_id) VALUES (8, 'Экспорт проекта', 'fa fa-cloud-upload', 0);
INSERT INTO {{%task_type}} (id, name, icon, status_id) VALUES (9, 'Обновление YM URL', 'fa fa-refresh', 0);
INSERT INTO {{%task_type}} (id, name, icon, status_id) VALUES (7, 'Просчет проекта', 'fa fa-calculator', 0);
INSERT INTO {{%task_type}} (id, name, icon, status_id) VALUES (10, 'Парсинг', 'fa fa-code', 0);
INSERT INTO {{%task_type}} (id, name, icon, status_id) VALUES (11, 'Обработка файла', 'fa fa-cloud-upload', 0);
INSERT INTO {{%task_type}} (id, name, icon, status_id) VALUES (12, 'Ошибки товаров конкрунетов', 'fa fa-bug', 0);
INSERT INTO {{%task_type}} (id, name, icon, status_id) VALUES (13, 'Построение урлов парсинга', 'fa fa-code', 0);

INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (0, 'Статус', 'Status', 'app\models\\enum\Status', 'status', 'enum', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (1, 'Пользователи', 'User', 'app\models\\reference\User', 'user', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (2, 'Торговая площадка', 'Source', 'app\models\\enum\Source', 'source', 'enum', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (3, 'Бренды', 'Brand', 'app\models\\reference\Brand', 'brand', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (4, 'Рубрики', 'Category', 'app\models\\reference\Category', 'category', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (5, 'Тип цены Прайсформера', 'PriceFormerType', 'app\models\\reference\PriceFormerType', 'price-former-type', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (6, 'Регионы', 'Region', 'app\models\\enum\Region', 'region', 'enum', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (7, 'Конкуренты', 'Competitor', 'app\models\\reference\Competitor', 'competitor', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (52, 'Связь проектов парсинга и расчета', 'ParsingProjectProject', 'app\models\cross\ParsingProjectProject', 'parsing-project-project', 'cross', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (10, 'Товары', 'Item', 'app\models\\reference\Item', 'item', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (11, 'Товары конкурентов', 'CompetitorItem', 'app\models\\reference\CompetitorItem', 'competitor-item', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (12, 'Алгоритм средней цены', 'SelectPriceLogic', 'app\models\\enum\SelectPriceLogic', 'select-price-logic', 'enum', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (13, 'Режим выгрузки цен', 'PriceExportMode', 'app\models\\enum\PriceExportMode', 'price-export-mode', 'enum', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (14, 'Режим выбора конкурентов', 'CompetitionMode', 'app\models\\enum\CompetitionMode', 'competition-mode', 'enum', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (15, 'Связь товар-рубрика', 'CategoryItem', 'app\models\cross\CategoryItem', 'category-item', 'cross', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (17, 'Спарсенные цены', 'PriceParsed', 'app\models\pool\PriceParsed', 'price-parsed', 'pool', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (19, 'Статус расчета проекта', 'ProjectExecutionStatus', 'app\models\\enum\ProjectExecutionStatus', 'project-execution-status', 'enum', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (20, 'Проекты', 'Project', 'app\models\\reference\Project', 'project', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (26, 'Торговые площадки проекта', 'ProjectSource', 'app\models\cross\ProjectSource', 'project-source', 'cross', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (56, 'Скриншоты', 'Screenshot', 'app\models\pool\Screenshot', 'screenshot', 'pool', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (57, 'Регионы проекта', 'ProjectRegion', 'app\models\cross\ProjectRegion', 'project-region', 'cross', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (30, 'Дерево категорий', 'CategoryCategory', 'app\models\cross\CategoryCategory', 'category-category', 'cross', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (31, 'Тип ошибки', 'ErrorType', 'app\models\\enum\ErrorType', 'error-type', 'enum', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (32, 'Ошибки', 'Error', 'app\models\\register\Error', 'error', 'register', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (33, 'Обмен данными', 'ExchangeSystem', 'app\models\\reference\ExchangeSystem', 'exchange-system', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (34, 'Регист на импорт', 'ExchangeImport', 'app\models\\register\ExchangeImport', 'exchange-import', 'register', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (35, 'Регист на экспорт', 'ExchangeExport', 'app\models\\register\ExchangeExport', 'exchange-export', 'register', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (36, 'Тип файла', 'FileFormat', 'app\models\\enum\FileFormat', 'file-format', 'enum', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (39, 'Названия кокурентов', 'CompetitorShopName', 'app\models\\reference\CompetitorShopName', 'competitor-shop-name', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (40, 'Домены конкурентов', 'CompetitorShopDomain', 'app\models\\reference\CompetitorShopDomain', 'competitor-shop-domain', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (41, 'YMID конкурентов', 'CompetitorShopIndex', 'app\models\\reference\CompetitorShopIndex', 'competitor-shop-index', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (42, 'Тип процесса', 'TaskType', 'app\models\\enum\TaskType', 'task-type', 'enum', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (43, 'Статус процесса', 'TaskStatus', 'app\models\\enum\TaskStatus', 'task-status', 'enum', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (44, 'Процесс', 'Task', 'app\models\\register\Task', 'task', 'register', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (38, 'Работа с файлами', 'FileExchange', 'app\models\\register\FileExchange', 'file-exchange', 'register', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (37, 'Настройка работы с файлами', 'FileExchangeSettings', 'app\models\\reference\FileExchangeSettings', 'file-exchange-settings', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (59, 'Маски', 'Masks', 'app\models\\reference\Masks', 'masks', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (25, 'Просчёт проекта', 'ProjectExecution', 'app\models\document\ProjectExecution', 'project-execution', 'document', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (24, 'Рубрики конкурента проекта', 'ProjectCompetitorCategory', 'app\models\\reference\ProjectCompetitorCategory', 'project-competitor-category', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (23, 'Бренды конкурента проекта', 'ProjectCompetitorBrand', 'app\models\\reference\ProjectCompetitorBrand', 'project-competitor-brand', 'register', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (18, 'Цены конкурентов', 'PriceRefined', 'app\models\pool\PriceRefined', 'price-refined', 'pool', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (29, 'История расчета цен', 'LogPriceCalculation', 'app\models\pool\LogPriceCalculation', 'log-price-calculation', 'pool', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (21, 'Номенклатура проекта', 'ProjectItem', 'app\models\\reference\ProjectItem', 'project-item', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (22, 'Конкуренты проекта', 'ProjectCompetitor', 'app\models\\reference\ProjectCompetitor', 'project-competitor', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (45, 'Контроль КС', 'ReportKeywordsControl', 'app\models\\reference\ReportKeywordsControl', 'report-keywords-control', 'register', 28, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (47, 'Темы проектов', 'ProjectTheme', 'app\models\\reference\ProjectTheme', 'project-theme', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (8, 'Настройки журналов', 'JournalSettings', 'app\models\\reference\JournalSettings', 'journal-settings', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (16, 'Статус парсинга', 'ParsingStatus', 'app\models\\enum\ParsingStatus', 'parsing-status', 'enum', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (48, 'Настройки парсинга', 'ParsingProject', 'app\models\\reference\ParsingProject', 'parsing-project', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (49, 'Регионы парсинга', 'ParsingProjectRegion', 'app\models\cross\ParsingProjectRegion', 'parsing-project-region', 'cross', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (50, 'Парсинг', 'Parsing', 'app\models\\register\Parsing', 'parsing', 'register', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (51, 'Расписание', 'Schedule', 'app\models\\reference\Schedule', 'schedule', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (61, 'Ошибки парсинга', 'ParsingError', 'app\models\pool\ParsingError', 'parsing-error', 'pool', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (28, 'История выполнения проекта', 'LogProjectExecution', 'app\models\pool\LogProjectExecution', 'log-project-execution', 'pool', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (27, 'Расчитанные цены', 'PriceCalculated', 'app\models\pool\PriceCalculated', 'price-calculated', 'pool', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (46, 'Обзорная таблица', 'ReportCalculationOverview', 'app\models\pool\ReportCalculationOverview', 'report-calculation-overview', 'pool', 28, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (53, 'Статус', 'PriceParsedStatus', 'app\models\\enum\PriceParsedStatus', 'price-parsed-status', 'enum', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (54, 'Буффер спарсенных цен', 'ParsingBuffer', 'app\models\pool\ParsingBuffer', 'parsing-buffer', 'pool', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (60, 'Роботы', 'Robot', 'app\models\\reference\Robot', 'robot', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (62, 'Связь проектов парсинга и масок', 'ParsingProjectMasks', 'app\models\cross\ParsingProjectMasks', 'parsing-project-masks', 'cross', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (55, 'Связь проектов и типов цен', 'ProjectPriceFormerType', 'app\models\cross\ProjectPriceFormerType', 'project-price-former-type', 'cross', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (63, 'Задачи Антикапчи', 'AntiCaptchaTask', 'app\models\\register\AntiCaptchaTask', 'anti-captcha-task', 'register', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (64, 'Фильтр брендов', 'BrandFilter', 'app\models\\reference\BrandFilter', 'brand-filter', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (65, 'Статус идентификации', 'HoradricCubeStatus', 'app\models\\enum\HoradricCubeStatus', 'horadric-cube-status', 'enum', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (66, 'Журнал идентификации', 'HoradricCube', 'app\models\\register\HoradricCube', 'horadric-cube', 'register', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (67, 'Типы обработки файлов', 'FileProcessingSettings', 'app\models\\reference\FileProcessingSettings', 'file-processing-settings', 'reference', null, false, true);
INSERT INTO {{%entity}} (id, name, alias, class_name, action, entity_type, parent_id, is_logging, is_enabled) VALUES (68, 'Обработка файлов', 'FileProcessing', 'app\models\\register\FileProcessing', 'file-processing', 'register', null, false, true);

INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (17, 'Северо-Запад РФ', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (18, 'Петрозаводск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (19, 'Сыктывкар', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (22, 'Калининград', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (23, 'Мурманск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (26, 'Юг РФ', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (28, 'Махачкала', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (30, 'Нальчик', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (40, 'Поволжье', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (52, 'Урал', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (57, 'Ханты-Мансийск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (58, 'Салехард', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (59, 'Сибирь', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (62, 'Красноярск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (63, 'Иркутск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (64, 'Кемерово', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (65, 'Новосибирск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (66, 'Омск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (67, 'Томск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (68, 'Чита', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (73, 'Дальний Восток', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (74, 'Якутск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (75, 'Владивосток', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (76, 'Хабаровск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (77, 'Благовещенск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (78, 'Петропавловск-Камчатский', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (79, 'Магадан', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (80, 'Южно-Сахалинск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (84, 'США', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (86, 'Атланта', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (87, 'Вашингтон', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (89, 'Детройт', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (90, 'Сан-Франциско', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (91, 'Сиэтл', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (93, 'Аргентина', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (94, 'Бразилия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (95, 'Канада', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (96, 'Германия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (97, 'Гейдельберг', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (98, 'Кельн', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (99, 'Мюнхен', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (100, 'Франкфурт-на-Майне', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (101, 'Штутгарт', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (102, 'Великобритания', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (111, 'Европа', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (113, 'Австрия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (114, 'Бельгия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (115, 'Болгария', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (116, 'Венгрия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (117, 'Литва', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (118, 'Нидерланды', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (119, 'Норвегия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (120, 'Польша', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (121, 'Словакия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (122, 'Словения', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (123, 'Финляндия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (124, 'Франция', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (125, 'Чехия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (126, 'Швейцария', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (127, 'Швеция', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (129, 'Беер-Шева', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (130, 'Иерусалим', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (131, 'Тель-Авив', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (132, 'Хайфа', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (134, 'Китай', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (135, 'Корея', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (137, 'Япония', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (138, 'Австралия и Океания', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (139, 'Новая Зеландия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (141, 'Днепропетровск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (142, 'Донецк', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (143, 'Киев', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (144, 'Львов', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (145, 'Одесса', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (146, 'Симферополь', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (147, 'Харьков', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (148, 'Николаев', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (149, 'Беларусь', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (153, 'Брест', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (154, 'Витебск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (155, 'Гомель', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (157, 'Минск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (158, 'Могилев', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (159, 'Казахстан', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (162, 'Алматы', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (163, 'Астана', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (164, 'Караганда', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (165, 'Семей', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (166, 'СНГ', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (167, 'Азербайджан', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (168, 'Армения', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (169, 'Грузия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (170, 'Туркмения', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (2, 'Санкт-Петербург', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (3, 'Центр РФ', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (6, 'Калуга', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (4, 'Белгород', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (7, 'Кострома', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (8, 'Курск', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (9, 'Липецк', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10, 'Орел', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11, 'Рязань', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (12, 'Смоленск', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (13, 'Тамбов', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (14, 'Тверь', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (15, 'Тула', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (16, 'Ярославль', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20, 'Архангельск', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (21, 'Вологда', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (33, 'Владикавказ', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (35, 'Краснодар', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (36, 'Ставрополь', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (37, 'Астрахань', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (38, 'Волгоград', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (39, 'Ростов-на-Дону', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (41, 'Йошкар-Ола', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (42, 'Саранск', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (43, 'Казань', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (44, 'Ижевск', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (45, 'Чебоксары', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (46, 'Киров', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (47, 'Нижний Новгород', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (48, 'Оренбург', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (49, 'Пенза', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (50, 'Пермь', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (51, 'Самара', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (53, 'Курган', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (54, 'Екатеринбург', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (55, 'Тюмень', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (56, 'Челябинск', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (171, 'Узбекистан', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (172, 'Уфа', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (177, 'Берлин', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (178, 'Гамбург', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (179, 'Эстония', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (180, 'Сербия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (181, 'Израиль', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (183, 'Азия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (187, 'Украина', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (190, 'Павлодар', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (197, 'Барнаул', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (198, 'Улан-Удэ', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (200, 'Лос-Анджелес', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (202, 'Нью-Йорк', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (203, 'Дания', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (204, 'Испания', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (205, 'Италия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (206, 'Латвия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (207, 'Киргизия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (208, 'Молдова', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (209, 'Таджикистан', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (210, 'Объединенные Арабские Эмираты', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (211, 'Австралия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (213, 'Москва', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (214, 'Долгопрудный', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (215, 'Дубна', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (216, 'Зеленоград', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (217, 'Пущино', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (219, 'Черноголовка', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (221, 'Чимкент', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (222, 'Луганск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (223, 'Бостон', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (225, 'Россия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (237, 'Новокузнецк', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (238, 'Новочеркасск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (241, 'Африка', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (245, 'Арктика и Антарктика', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (246, 'Греция', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (382, 'Общероссийские', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (959, 'Севастополь', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (960, 'Запорожье', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (961, 'Хмельницкий', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (962, 'Херсон', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (963, 'Винница', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (964, 'Полтава', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (965, 'Сумы', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (966, 'Чернигов', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (967, 'Обнинск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (969, 'Выборг', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (973, 'Сургут', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (974, 'Находка', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (975, 'Бийск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (976, 'Братск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (977, 'Крым', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (980, 'Страны Балтии', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (983, 'Турция', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (994, 'Индия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (995, 'Таиланд', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (1004, 'Ближний Восток', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (1056, 'Египет', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (1058, 'Туапсе', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (1091, 'Нижневартовск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (1092, 'Назрань', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (1093, 'Майкоп', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (1094, 'Элиста', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (1095, 'Абакан', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (1104, 'Черкесск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (1106, 'Грозный', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (1107, 'Анапа', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10002, 'Северная Америка', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10003, 'Южная Америка', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10069, 'Мальта', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10083, 'Хорватия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10174, 'Санкт-Петербург и Ленинградская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10176, 'Ненецкий АО', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10231, 'Республика Алтай', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10233, 'Республика Тыва', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10243, 'Еврейская автономная область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10251, 'Чукотский автономный округ', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10274, 'Гродно', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10303, 'Талдыкорган', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10306, 'Усть-Каменогорск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10343, 'Житомир', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10345, 'Ивано-Франковск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10347, 'Кривой Рог', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10355, 'Ровно', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10357, 'Тернополь', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10358, 'Ужгород', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10363, 'Черкассы', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10365, 'Черновцы', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10366, 'Мариуполь', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10367, 'Мелитополь', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10369, 'Белая Церковь', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10645, 'Белгородская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10650, 'Брянская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10656, 'Александров', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10658, 'Владимирская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10661, 'Гусь-Хрустальный', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10671, 'Суздаль', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10672, 'Воронежская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10687, 'Ивановская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10693, 'Калужская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10699, 'Костромская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10705, 'Курская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10712, 'Липецкая область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10716, 'Балашиха', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10719, 'Видное', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10723, 'Дмитров', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10725, 'Домодедово', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10733, 'Клин', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (191, 'Брянск', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (193, 'Воронеж', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (194, 'Саратов', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (195, 'Ульяновск', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (235, 'Магнитогорск', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (239, 'Сочи', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (240, 'Тольятти', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (968, 'Череповец', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (970, 'Новороссийск', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (971, 'Таганрог', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (972, 'Дзержинск', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10649, 'СтарыйОскол', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10734, 'Коломна', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10735, 'Красногорск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10738, 'Люберцы', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10740, 'Мытищи', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10742, 'Ногинск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10743, 'Одинцово', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10745, 'Орехово-Зуево', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10746, 'Павловский Посад', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10747, 'Подольск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10748, 'Пушкино', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10750, 'Раменское', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10752, 'Сергиев Посад', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10754, 'Серпухов', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10755, 'Солнечногорск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10756, 'Ступино', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10758, 'Химки', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10761, 'Чехов', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10765, 'Щелково', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10772, 'Орловская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10776, 'Рязанская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10795, 'Смоленская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10802, 'Тамбовская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10819, 'Тверская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10820, 'Ржев', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10832, 'Тульская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10837, 'Переславль', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10840, 'Углич', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10841, 'Ярославская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10842, 'Архангельская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10849, 'Северодвинск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10853, 'Вологодская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10857, 'Калининградская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10867, 'Гатчина', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10894, 'Апатиты', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10897, 'Мурманская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10904, 'Новгородская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10926, 'Псковская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10928, 'ВеликиеЛуки', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10933, 'Республика Карелия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10937, 'Сортавала', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10939, 'Республика Коми', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10945, 'Ухта', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10946, 'Астраханская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10950, 'Волгоградская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10987, 'Армавир', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10990, 'Геленджик', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10993, 'Ейск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10995, 'Краснодарский край', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11004, 'Республика Адыгея', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11010, 'Республика Дагестан', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11012, 'Республика Ингушетия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11013, 'Республика Кабардино-Балкария', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11015, 'Республика Калмыкия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11020, 'Карачаево-Черкесская Республика', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11021, 'Республика Северная Осетия-Алания', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11024, 'Чеченская Республика', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11029, 'Ростовская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11036, 'Волгодонск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11043, 'Каменск-Шахтинский', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11057, 'Ессентуки', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11062, 'Кисловодск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11063, 'Минеральные Воды', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11064, 'Невинномысск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11069, 'Ставропольский край', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11070, 'Кировская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11071, 'Кирово-Чепецк', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11077, 'Республика Марий Эл', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11079, 'Нижегородская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11080, 'Арзамас', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11083, 'Саров', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11084, 'Оренбургская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11095, 'Пензенская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11108, 'Пермский край', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11110, 'Соликамск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11111, 'Республика Башкортостан', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11114, 'Нефтекамск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11115, 'Салават', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11116, 'Стерлитамак', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11117, 'Республика Мордовия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11119, 'Татарстан', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11131, 'Самарская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11132, 'Жигулевск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11139, 'Сызрань', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11143, 'Балаково', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11146, 'Саратовская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11148, 'Удмуртская республика', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11150, 'Глазов', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11152, 'Сарапул', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11153, 'Ульяновская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11155, 'Димитровград', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11156, 'Чувашская республика', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11158, 'Курганская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11162, 'Свердловская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11164, 'Каменск-Уральский', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11170, 'Новоуральск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11171, 'Первоуральск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11173, 'Ишим', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11175, 'Тобольск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11176, 'Тюменская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11193, 'Ханты-Мансийский АО', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11202, 'Златоуст', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11212, 'Миасс', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11214, 'Озерск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11217, 'Сатка', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11218, 'Снежинск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11225, 'Челябинская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10838, 'Ростов', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11127, 'Нижнекамск', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11091, 'Орск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11147, 'Энгельс', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11168, 'Нижний Тагил', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11232, 'Ямало-Ненецкий АО', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11235, 'Алтайский край', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11251, 'Рубцовск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11256, 'Ангарск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11266, 'Иркутская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11273, 'Усть-Илимск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11282, 'Кемеровская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11287, 'Междуреченск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11291, 'Прокопьевск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11302, 'Ачинск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11306, 'Кайеркан', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11309, 'Красноярский край', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11311, 'Норильск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11314, 'Бердск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11316, 'Новосибирская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11318, 'Омская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11319, 'Горно-Алтайск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11330, 'Республика Бурятия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11333, 'Кызыл', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11340, 'Республика Хакасия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11341, 'Саяногорск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11351, 'Северск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11353, 'Томская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11374, 'Белогорск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11375, 'Амурская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11391, 'Тында', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11393, 'Биробиджан', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11398, 'Камчатский край', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11403, 'Магаданская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11409, 'Приморский край', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11426, 'Уссурийск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11443, 'Республика Саха (Якутия)', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11450, 'Сахалинская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11453, 'Комсомольск-на-Амуре', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11457, 'Хабаровский край', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11458, 'Анадырь', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11464, 'Керчь', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11470, 'Ялта', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20040, 'Выкса', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20044, 'Кстово', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20086, 'Железногорск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20221, 'Кировоград', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20222, 'Луцк', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20258, 'Сатис', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20271, 'Мексика', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20273, 'Актобе', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20523, 'Электросталь', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20529, 'Львовская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20530, 'Закарпатская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20531, 'Тернопольская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20532, 'Ивано-Франковская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20533, 'Черновицкая область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20534, 'Ровенская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20535, 'Хмельницкая область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20536, 'Донецкая область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20537, 'Днепропетровская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20538, 'Харьковская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20539, 'Запорожская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20540, 'Луганская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20541, 'Одесская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20542, 'Херсонская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20543, 'Николаевская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20544, 'Киевская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20545, 'Винницкая область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20546, 'Черкасская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20547, 'Житомирская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20548, 'Кировоградская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20549, 'Полтавская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20550, 'Волынская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20551, 'Черниговская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20552, 'Сумская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20554, 'Краматорск', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20571, 'Жуковский', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20574, 'Кипр', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20674, 'Троицк', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20728, 'Королёв', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (20809, 'Кокшетау', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (21609, 'Кременчуг', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (21610, 'Черногория', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (21621, 'Реутов', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (21622, 'Железнодорожный', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (21949, 'Забайкальский край', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (24876, 'Макеевка', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (26034, 'Жодино', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29386, 'Абхазия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29387, 'Южная Осетия', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29403, 'Акмолинская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29404, 'Актюбинская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29406, 'Алматинская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29407, 'Атырауская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29408, 'Восточно-Казахстанская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29409, 'Жамбылская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29410, 'Западно-Казахстанская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29411, 'Карагандинская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29412, 'Костанайская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29413, 'Кызылординская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29414, 'Мангистауская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29415, 'Павлодарская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29416, 'Северо-Казахстанская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29417, 'Южно-Казахстанская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29629, 'Могилевская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29630, 'Минская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29631, 'Гомельская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29632, 'Брестская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29633, 'Витебская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (29634, 'Гродненская область', null, 0, false);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (1, 'Москва и область', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (24, 'Новгород', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (5, 'Иваново', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (25, 'Псков', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (192, 'Владимир', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (236, 'Набережные Челны', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10664, 'Ковров', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10668, 'Муром', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10830, 'Новомосковск', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10839, 'Рыбинск', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (10951, 'Волжский', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11053, 'Шахты', null, 0, true);
INSERT INTO {{%region}} (id, name, parent_id, status_id, is_ours) VALUES (11067, 'Пятигорск', null, 0, true);
SQL;
}
